CREATE TABLE `dbc_gameobjectdisplayinfo` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`i1` INT(11) NOT NULL DEFAULT '0',
	`i2` INT(11) NOT NULL DEFAULT '0',
	`i3` INT(11) NOT NULL DEFAULT '0',
	`i4` INT(11) NOT NULL DEFAULT '0',
	`i5` INT(11) NOT NULL DEFAULT '0',
	`i6` INT(11) NOT NULL DEFAULT '0',
	`i7` INT(11) NOT NULL DEFAULT '0',
	`i8` INT(11) NOT NULL DEFAULT '0',
	`i9` INT(11) NOT NULL DEFAULT '0',
	`i10` INT(11) NOT NULL DEFAULT '0',
	`f1` FLOAT NOT NULL DEFAULT '0',
	`f2` FLOAT NOT NULL DEFAULT '0',
	`f3` FLOAT NOT NULL DEFAULT '0',
	`f4` FLOAT NOT NULL DEFAULT '0',
	`f5` FLOAT NOT NULL DEFAULT '0',
	`f6` FLOAT NOT NULL DEFAULT '0',
	`i11` INT(11) NOT NULL DEFAULT '0',
	`f7` FLOAT NOT NULL DEFAULT '0',
	`f8` FLOAT NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`),
	INDEX `idx_name` (`name`)
)
COMMENT='Used for game object patch'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
